"""Auto-generated VID/PID lookup from EEPROM metadata."""

# Generated by scripts/generate_hexpansion_names.py
# Source: /home/alex/emf/racecondition/hexpansion-firmwares

VID_PID_TO_FRIENDLY_NAME = {
    (0x1337, 0x9009): 'GooglyEye',
    (0x1337, 0xAEAE): 'ArcadeEdition',
    (0x4291, 0x1717): 'InfraRed',
    (0x4291, 0x1830): 'UK Map',
    (0x4291, 0x5E6A): 'MegaDrive',
    (0x7CAB, 0xBEAC): 'GPS',
    (0xBAD3, 0x31F1): 'EMFWiFi',
    (0xBAD3, 0x4EEB): 'keepdeck',
    (0xCAFE, 0x1295): 'GPS',
    (0xCAFE, 0x5E6A): 'MegaDrive',
    (0xCAFE, 0xCAFF): 'Caffeine!',
    (0xCBCB, 0x5000): 'HexCurent',
}


def get_friendly_name(vid: int, pid: int) -> str | None:
    return VID_PID_TO_FRIENDLY_NAME.get((vid, pid))
