[app]
name = "Race Condition"
category = "Games"

[entry]
class = "RaceConditionApp"

[metadata]
author = "Alex Rea"
license = "MIT"
url = "https://github.com/area/racecondition"
description = "A co-operative shouting game for 1-6 players"
version = "0.0.1"
