"""Auto-generated VID/PID lookup from EEPROM metadata."""

# Generated by scripts/generate_hexpansion_names.py
# Source: /home/alex/emf/spaceteam/hexpansion-firmwares

VID_PID_TO_FRIENDLY_NAME = {
    (0x1337, 0x9009): 'GooglyEye',
    (0x1337, 0xAEAE): 'ArcadeEdition',
    (0x4291, 0x1717): 'InfraRed',
    (0x4291, 0x1830): 'UK Map',
    (0x4291, 0x5E6A): 'MegaDrive',
    (0xCAFE, 0x1295): 'GPS',
    (0xCAFE, 0x5E6A): 'MegaDrive',
    (0xCAFE, 0xCAFF): 'Caffeine!',
}


def get_friendly_name(vid: int, pid: int) -> str | None:
    return VID_PID_TO_FRIENDLY_NAME.get((vid, pid))
