#!/usr/bin/env python3
"""Generate VID/PID friendly-name lookup from hexpansion EEPROM manifests."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


# Temporary aliases for VID/PID pairs that should resolve to known devices
# even when not present in EEPROM manifests yet.
MANUAL_FRIENDLY_NAME_OVERRIDES: dict[tuple[int, int], str] = {
    (0xCAFE, 0x5E6A): "MegaDrive",
}


def parse_hex(value: str, field_name: str, source_file: Path) -> int:
    try:
        return int(str(value), 16)
    except (TypeError, ValueError) as exc:
        raise ValueError(
            f"Invalid {field_name} '{value}' in {source_file}"
        ) from exc


def collect_friendly_names(source_root: Path) -> dict[tuple[int, int], str]:
    mapping: dict[tuple[int, int], str] = {}

    for eeprom_file in sorted(source_root.rglob("eeprom.json")):
        data = json.loads(eeprom_file.read_text(encoding="utf-8"))

        if "vid" not in data or "pid" not in data:
            continue

        name = data.get("friendly_name")
        if not isinstance(name, str) or not name.strip():
            continue

        vid = parse_hex(data["vid"], "vid", eeprom_file)
        pid = parse_hex(data["pid"], "pid", eeprom_file)
        key = (vid, pid)

        existing_name = mapping.get(key)
        if existing_name and existing_name != name:
            raise ValueError(
                "Conflicting friendly names for "
                f"VID/PID 0x{vid:04X}/0x{pid:04X}: "
                f"'{existing_name}' vs '{name}' ({eeprom_file})"
            )

        mapping[key] = name

    return mapping


def render_module(mapping: dict[tuple[int, int], str], source_root: Path) -> str:
    lines = [
        '"""Auto-generated VID/PID lookup from EEPROM metadata."""',
        "",
        "# Generated by scripts/generate_hexpansion_names.py",
        f"# Source: {source_root.as_posix()}",
        "",
        "VID_PID_TO_FRIENDLY_NAME = {",
    ]

    for (vid, pid), name in sorted(mapping.items()):
        lines.append(f"    (0x{vid:04X}, 0x{pid:04X}): {name!r},")

    lines.extend(
        [
            "}",
            "",
            "",
            "def get_friendly_name(vid: int, pid: int) -> str | None:",
            "    return VID_PID_TO_FRIENDLY_NAME.get((vid, pid))",
            "",
        ]
    )

    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Extract VID/PID friendly names from EEPROM JSON files and "
            "generate a Python lookup module."
        )
    )
    parser.add_argument(
        "--source",
        default="hexpansion-firmwares",
        help="Path to the firmware repository root.",
    )
    parser.add_argument(
        "--output",
        default="app/hexpansion_names.py",
        help="Path to the generated Python module.",
    )

    args = parser.parse_args()

    source_root = Path(args.source).resolve()
    output_path = Path(args.output).resolve()

    if not source_root.exists():
        raise FileNotFoundError(f"Source path not found: {source_root}")

    mapping = collect_friendly_names(source_root)
    mapping.update(MANUAL_FRIENDLY_NAME_OVERRIDES)
    module_text = render_module(mapping, source_root)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(module_text, encoding="utf-8")

    print(
        f"Wrote {len(mapping)} VID/PID mappings to "
        f"{output_path.as_posix()}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
